### ISSUE TITLE
EXC_BAD_ACCESS Attempted to dereference garbage pointer Originated at or in a subcall of __cxa_throw

### ISSUE THREAD

**Issue by moret** [EkoLabs/react-native-background-downloader#35]
Hi! I've started using `react-native-background-downloader` in production a couple of weeks ago. Since switching from manually using `rn-fetch-blob` to it however I noticed a spike in crashes on iOS. We have Sentry installed, the error I'm seeing is:

```
EXC_BAD_ACCESS
Attempted to dereference garbage pointer 0xf2697a0a0.
Originated at or in a subcall of __cxa_throw
Called from:
CFNetwork
__113-[NSURLSession delegate_downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:completionHandler:]_block_invoke
```
<img width="1049" alt="Screenshot 2019-07-15 at 08 14 32" src="https://user-images.githubusercontent.com/620156/61213288-0006b900-a6db-11e9-8693-a4dc99ffadbd.png">
I can't reproduce the crash locally, unfortunately, but I hope someone might shine a light on it.

**Comment by ptelad** [comment]
Hi,
Are you using version 2.1.0?

**Comment by moret** [comment]
Hi @ptelad, thank you for the quick reply! I have a new release waiting to be approved by Apple using 2.1.0, but those statistics are indeed from `2.0.1` which was the latest version at the time. I'll come back when Apple finishes reviewing.

**Comment by moret** [comment]
Hi @ptelad . Unfortunately it seems to be happening even after updating to `2.1.0`. The new app release using it was approved last night by Apple, with the same error showing up on Sentry. 8(

```
EXC_BAD_ACCESS
Attempted to dereference garbage pointer 0x482e97820.
Originated at or in a subcall of __cxa_throw
Called from:
CFNetwork
__113-[NSURLSession delegate_downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:completionHandler:]_block_invoke
```

**Comment by FrankGoortani** [comment]
I have the same issue. It happens when I trigger multiple downloads. below is my crash report:
`Fatal Exception: NSInvalidArgumentException
0  CoreFoundation                 0x1d361127c __exceptionPreprocess
1  libobjc.A.dylib                0x1d27eb9f8 objc_exception_throw
2  CoreFoundation                 0x1d358ace8 _CFArgv
3  CoreFoundation                 0x1d35055c4 -[__NSPlaceholderArray initWithObjects:count:]
4  CoreFoundation                 0x1d34fed88 +[NSArray arrayWithObjects:count:]
5  CoreFoundation                 0x1d34fff98 -[NSDictionary allValues]
6  maktub                         0x104d57a1c -[RNBackgroundDownloader URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:] + 238 (RNBackgroundDownloader.m:238)
7  CFNetwork                      0x1d3d94b58 __113-[NSURLSession delegate_downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:completionHandler:]_block_invoke
8  Foundation                     0x1d4075ef8 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__
9  Foundation                     0x1d3f823e0 -[NSBlockOperation main]
10 Foundation                     0x1d3f818c8 -[__NSOperationInternal _start:]
11 Foundation                     0x1d4077c7c __NSOQSchedule_f
12 libdispatch.dylib              0x1d3050a38 _dispatch_call_block_and_release
13 libdispatch.dylib              0x1d30517d4 _dispatch_client_callout
14 libdispatch.dylib              0x1d2ff6018 _dispatch_continuation_pop$VARIANT$mp
15 libdispatch.dylib              0x1d2ff56dc _dispatch_async_redirect_invoke
16 libdispatch.dylib              0x1d300202c _dispatch_root_queue_drain
17 libdispatch.dylib              0x1d30028d0 _dispatch_worker_thread2`

**Comment by FrankGoortani** [comment]
@ptelad Please help with this issue!! My app got rejected bbyb the iOS reviewers because of the crash!!

**Comment by ptelad** [comment]
Hey @moret and @FrankGoortani - I am terribly sorry but I have no Idea where to even start with this.
Please keep up with version to see if it's somehow fixed.
I would suggest maybe try to update your RN version if you haven't yet.

**Comment by moret** [comment]
@ptelad thank you for your response anyway! I'll keep monitoring and will try to get back if something changes. Feel free to keep the issue closed if you prefer, and whenever something comes up it can be reopened.

**Comment by mark-plukkido** [comment]
@ptelad Can you review my #43 for this issue? I was running into random SIGABRTs, EXC_BAD_ACCESS-es and serialization also hit a bug where the (de)serialization attempted to insert nil into a Dictionary. I'm assuming the delegate queue does not sync implicitly with the serializing thread, which causes one half of these problems.

There is also a set of stale pointer issues in `URLSession:downloadTask:didWriteData:totalBytesWritten:totalBytesExpectedToWrite:totalBytesExpectedToWrite` which also must be related to threading (even though the module uses an NSOperationQueue to serialize delegate execution. This only comes up intermittently, if you continuously try to download 200+ files in parallel. 

All the crash reports in this issue I've seen in my testing of the module and I believe this small patch solves all of them and many other stale pointer issues.

Modification is tested on IOS Simulator and iPhone 6S Plus.

**Comment by ptelad** [comment]
Thank you so much @mark-plukkido ! Let's hope this works.
I just published version 2.1.2 with you fix, @moret please try it out

**Comment by moret** [comment]
@NirvaleO hi, sorry to bother you, but since I don't currently have easy access to the `learn` app to upgrade, release, and follow up on the crash rate after Apple approves the app, would you mind doing it since you do have access right now? Thank you! 👨‍🎓

**Comment by FrankGoortani** [comment]
This didn't solve my crashing problems. The only solution I found so far is to download files one by one..

**Comment by NirvaleO** [comment]
I've updated the app @moret was maintaining, made a few changes and things have gotten quite better. :)
What seemed to be the cause of the problem was that we were trying to call `task.stop()` after it had some error. But, if I'm not mistaken, the task were already deleted by the Lib. (If that's not the case plz enlighten me as native code is not my strongest feat).
Anyway the number of errors dropped back to "normal". 🙌 
![image](https://user-images.githubusercontent.com/6654745/65636916-94ce4280-dfb9-11e9-9a18-f0b54c0da9fb.png)
